// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbIWjQtv7TXxYKxyo8kWEV8tyQKOopRHM',
    appId: '1:948131229423:android:e6a9561150ba95e192f51a',
    messagingSenderId: '948131229423',
    projectId: 'fooddelivery-7bd5e',
    storageBucket: 'fooddelivery-7bd5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQi2CKnvCv7y4QBsop3aiOzCW5Y_livJc',
    appId: '1:948131229423:ios:89cdc91543b0ab0b92f51a',
    messagingSenderId: '948131229423',
    projectId: 'fooddelivery-7bd5e',
    storageBucket: 'fooddelivery-7bd5e.firebasestorage.app',
    iosBundleId: 'ar.manosdelpueblo.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoIV5ewU0nIRVcjq2LMzsLocFvw2atGBw',
    appId: '1:948131229423:web:ac3ac8c442f4c1a292f51a',
    messagingSenderId: '948131229423',
    projectId: 'fooddelivery-7bd5e',
    authDomain: 'fooddelivery-7bd5e.firebaseapp.com',
    storageBucket: 'fooddelivery-7bd5e.firebasestorage.app',
    measurementId: 'G-RSL8R3WQK4',
  );

}